### ISSUE TITLE
viz instructions

### ISSUE THREAD

**Issue by Bernadetadad** [dms-viz/dms-viz.github.io#2]
Could you add instruction for the different selection options (dragging, clicking, how to deselect), maybe at the bottom of the page? It took me some time to figure out what's doing what and I had some sense before because I saw you do it but it might be useful for someone who never used this tool before.

**Comment by WillHannon-MCB** [comment]
There are instructions on the page, but you have to click on the little `?` on the top of the page like so: 

![Screenshot 2023-04-24 at 11 23 31 AM](https://user-images.githubusercontent.com/62000409/234083292-36353054-9d4d-4264-a6f2-d35ab69ad019.png)

I agree that this isn't super obvious. I think I'll add a little pop-up window that shows up when the user first click on the tool. Or, I'll have the instructions pop-up there by default. I'll explore the best way to do this.

**Comment by WillHannon-MCB** [comment]
I added a feature where the instructions are highlighted when the user first opens the page. 
![Screenshot 2023-04-27 at 4 38 24 PM](https://user-images.githubusercontent.com/62000409/235012750-37f6663c-849b-4ec0-8d19-cc9030d19853.png)
