### ISSUE TITLE
Download pdb file

### ISSUE THREAD

**Issue by Bernadetadad** [dms-viz/dms-viz.github.io#25]
If possible, would be great to be able to download a `.pdb` file for the dms-viz-produced visualization because sometimes it's useful to add in additional features to the structure that are outside what the dms-viz tool is used for.

**Comment by WillHannon-MCB** [comment]
Thinking about this more, I'm not sure if the visualization tool is the best place to implement this. The best I could do is return a PDB structure with the b-factors replaced with the value of a summary statistic for a single `condition`. I'd probably implement this in the [configuration tool](https://github.com/dms-viz/configure_dms_viz) if I did it. 

Also, I think that [`polyclonal`](https://github.com/jbloomlab/polyclonal) already has a method for this?

I'm going to close this for now, but I'll re-open it if I think of a better solution.
