### ISSUE TITLE
Allow to choose epitope colors

### ISSUE THREAD

**Issue by Bernadetadad** [dms-viz/dms-viz.github.io#26]
Maybe I missed this, but can we have an option to put in self-defined HEX color codes for epitopes?

**Comment by WillHannon-MCB** [comment]
Yep! In the [configure_dms_viz](https://github.com/dms-viz/configure_dms_viz) tool, there is an optional flag that let's you specify a list of colors, i.e.

```
--colors <color_list>: A list of colors for representing different epitopes.
```

**Comment by Bernadetadad** [comment]
Reopening issue. I tried running this and got just weird black coloring (zipped file with json). 
Also, can you add a clarification (maybe to docs) are sensitizing mutations also treated as separate epitope and can be colored this way?

```
configure-dms-viz \
    --input sera_1-05_avg_H5.csv \
    --name sera_1-05\
    --sitemap site_numbering_map_H5.csv \
    --metric escape_mean \
    --structure h5_2.pdb \
    --metric-name Escape \
    --output sera_1-05_c.json \
    --colors "['#F05D5E']"

```
[sera_1-05_c.json.zip](https://github.com/dms-viz/dms-viz.github.io/files/11899415/sera_1-05_c.json.zip)

**Comment by WillHannon-MCB** [comment]
The format is actually just a string separated by commas, i.e. 

```
--colors "#0072B2, #CC79A7, #4C3549, #009E73"
```

or in your case, just `--colors "#F05D5E"`. I'll update the documentation before closing this issue.

**Comment by WillHannon-MCB** [comment]
Also, if I understand your other question, sensitizing mutations are not treated as a separate epitope. The color of these mutations is determined by the inverse of the positive color that you supply. If it would be useful to specify the negative effect color could you open another issue and I'll try to implement that!

**Comment by WillHannon-MCB** [comment]
I added the format to the documentation in the `README` of [configure_dms_viz](https://github.com/dms-viz/configure_dms_viz).
