### ISSUE TITLE
Keep track of protein structure coordinates

### ISSUE THREAD

**Issue by Bernadetadad** [dms-viz/dms-viz.github.io#3]
It would be nice to reuse the same protein view coordinates so that you can download protein image positioned the same way for different mAbs.

**Comment by WillHannon-MCB** [comment]
In the most recent version of the tool, the protein's position, scale, and orientation will not change unless an different PDB file is loaded in. So, if you're using a file with multiple antibodies and the same structure, the coordinates will be preserved for each antibody.
