### ISSUE TITLE
Implement versioning using routes

### ISSUE THREAD

**Issue by WillHannon-MCB** [dms-viz/dms-viz.github.io#37]
We need to ensure that changes to the tool going forward don't break existing links. To do this, I'll implement a versioning scheme based on the URL route i.e., dms-viz.github.io/v1/, dms-viz.github.io/v2/, etc...

When breaking changes need to be implemented, I'll make a new subdirectory with the updated code and add a route to point to this code. 

To implement this, I'll need to refactor the structure of the source code and add a routing scheme.

**Comment by jbloom** [comment]
I guess what is important is that the versions are in the actual links though, right? We don't care about accessing old versions of the tool. But we want old links to always point to the appropriate version. So if the re-direction changes to new versions over time, would that not keep the problem as before? Or will the version be a required part of the URL?

**Comment by WillHannon-MCB** [comment]
Yep, they'd be links, i.e. dms-viz.github.io/v1/, dms-viz.github.io/v2/ and so on. Just like how the number at the end of this link (github.com/dms-viz/dms-viz.github.io/issues/37) represents a distinct issue, the version at the end of these links would represent a distinct version.

The version would be a required part of the URL in this implementation.
