### ISSUE TITLE
Integrate with dms-vep pipeline 

### ISSUE THREAD

**Issue by Bernadetadad** [dms-viz/dms-viz.github.io#6]
Is it possible to integrate this with `dms-vep` (presumably not hard because it only needs avg escape files and site references that we already have), so that we could get the `.json` files thought there as opposed to needing to run a separate pipeline.

**Comment by WillHannon-MCB** [comment]
I think this is a good idea, but I'm going to move this over to the [configure_dms_viz](https://github.com/dms-viz/configure_dms_viz) repository.
