### ISSUE TITLE
Reset structure doesn't work?

### ISSUE THREAD

**Issue by afrubin** [dms-viz/dms-viz.github.io#72]
According the the help button (?) on the site, I should be able to reset the structure by pressing R on the keyboard. However, this doesn't work for my browser.

I'm using Firefox 122.0 (64-bit) installed via Snap for Ubuntu

This issue is part of https://github.com/openjournals/joss-reviews/issues/6129

**Comment by WillHannon-MCB** [comment]
Two issues could cause this, both my fault:

1. The instructions should say `r` and not `R` (as in `r` + `shift`). 
2. I should also clarify in the instructions that by `reset`, I mean that if you've either _zoomed_ into the structure or _moved_ the structure within the window, pressing `r` will cause the structure to center in the window and reset to the default zoom. It will not reset the _orientation_ of the structure.

I'll update the instructions accordingly. If you still have issues, I assume it's a browser-specific error and I'll address that accordingly.
