### ISSUE TITLE
Add default filters

### ISSUE THREAD

**Issue by afrubin** [dms-viz/dms-viz.github.io#74]
It would be nice to see some sensible default filtering options. Some examples that could be exposed for every datasets include:
* Wildtype amino acids
* Completeness at that position (i.e. number of possible amino acid substitutions observed)
* Score range

I'm sure there are other examples of default filters that are broadly applicable that could be added as well, but including some of these would help users explore their data and get more value out of the tool.

This issue is part of https://github.com/openjournals/joss-reviews/issues/6129

**Comment by WillHannon-MCB** [comment]
I've added a default mutation count filter. I'll think about other useful default filters.

I'm not planning to add a filter for the 'wildtype' amino acid. I've gotten feedback from some users that they're using data that doesn't have a meaningful value for the 'wildtype' amino acid. In the future, I might make specifying a value for wildtype optional.
