### ISSUE TITLE
Docs typo?

### ISSUE THREAD

**Issue by jaredgalloway** [dms-viz/dms-viz.github.io#84]
Love the tool. Minor comment I noticed while looking at the docs - It seems there might be a typo with the documentation at the bottom of the [usins `dms-viz`](https://dms-viz.github.io/dms-viz-docs/visualizing-data/vignettes/#using-dms-viz) section. The documents state 

![Screenshot from 2024-04-30 07-06-16](https://github.com/dms-viz/dms-viz.github.io/assets/23087427/7c0b8863-a1e2-4624-b5d5-50e7a18df35e)

I'm assuming the example should have input JSON's, not CSV's. This was just a little confusing as the `--join-data` option for the `format` command might be mistaken for the `join` command.

**Comment by WillHannon-MCB** [comment]
Ah, thanks for the head up! Fixed now.
