### ISSUE TITLE
Floored effect coloring sometimes is carried over between datasets

### ISSUE THREAD

**Issue by Caleb-Carr** [dms-viz/dms-viz.github.io#91]
When visualizing different datasets (eg cell entry and antibody escape) on the same structure, it seems that the `Floor` effect coloring is sometimes carried over stochastically even though it is not selected. For example, if I am viewing antibody escape that is floored, switching to the cell entry dataset that is not floored sometimes results in the structure coloring to show up as floored. Reloading the page restores the coloring to the proper configuration but not sure if there is an easy fix for this?

**Comment by WillHannon-MCB** [comment]
And this is stochastic? Or, does it happen consistently for specific situations——like the dataset you're describing——but not for all situations?

Can you provide the specification file.

**Comment by WillHannon-MCB** [comment]
It looks like this is a consistent problem. The `chart` and `protein` objects appear to respond differently to `floor` when the dataset changes. The `chart` is behaving as expected, so the problem lies in the state of `floor` in the `protein` object.
