### ISSUE TITLE
be able to select just one condition to show lineplot for

### ISSUE THREAD

**Issue by jbloom** [dms-viz/dms-viz.github.io#97]
@WillHannon-MCB, maybe we can discuss this issue in person tomorrow, but briefly:

I am trying to use conditions to show many different antibodies. Here is the example JSON:
[prefusion_ab_escape.json](https://github.com/user-attachments/files/17612007/prefusion_ab_escape.json)
 
I would like to be able to pick just one antibody at a time to show on the line plot in addition to having them all overlaid with each other. But right now that isn't possible. I can click on them to just shown one on the structure at at time, but not to show just one in the lineplot.

Is it possible to add an option to make what I want possible?

See also the attached image:
<img width="1888" alt="Screenshot 2024-11-03 at 12 42 22 PM" src="https://github.com/user-attachments/assets/f839aa5d-bc03-428c-82ad-75ff44d7c0fa">

**Comment by WillHannon-MCB** [comment]
Are you talking about something like [this](https://dms-viz.github.io/v0/?data=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-vep%2FRABV_Pasteur_G_DMS%2Frefs%2Fheads%2Fmain%2Fresults%2Fdms-viz%2Fprefusion_ab_escape.json&sa=true&fi=%257B%2522cell_entry%2522%253A-5%257D&ce=%255B%2522CR4098%2522%252C%2522RVC68%2522%252C%2522RVC58%2522%255D&pe=RVC58)?

You can specify which antibodies (conditions) you want on the plot by clicking on the condition in the legend while holding down the option key (option+click). [I describe this in the second to last video in the 'Web Tool API' section of the documentation.](https://dms-viz.github.io/dms-viz-docs/visualizing-data/web-tool-api/#chart)

**Comment by jbloom** [comment]
OK, that does do what I was hoping, thanks!

Although is there a way to make this more facile? For instance on [this plot](https://dms-viz.github.io/v0/?data=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-vep%2FRABV_Pasteur_G_DMS%2Frefs%2Fheads%2Fmain%2Fresults%2Fdms-viz%2Fprefusion_ab_escape.json&pe=RVA122&fi=%257B%2522cell_entry%2522%253A-5%257D) if I want to show just one antibody I have to `option-click` on 7 other antibodies which is really slow to do as there is a lag for each one.

I feel like a very valuable feature for our work will be to show mmany antibodies and then just be able to select one (or a few) to show, and the current way makes that quite hard to do that easily.

Would it be possible to brainstorm ways to make this easier?

**Comment by jbloom** [comment]
@WillHannon-MCB, do you have an ETA on how long it will take to implement this? I would like to use `dms-viz` to present some datasets, but until this is done it is basically unusable so wanted to check.

**Comment by WillHannon-MCB** [comment]
@jbloom, sorry it's unsuable. There are two separate problems: (1) changing the input events that select conditions to show on the line plot, and (2) figuring out why things are running slowly.

For issue (1), I changed how you select conditions. You can still use `option + click` to select and deselect, but now, you can also `double-click` on a condition to show **only** that condition in the chart. All other conditions are automatically deselected.

Unfortunately, this doesn't fix the lag. When you select a condition, an event is fired that updates the legend, the chart, the protein, the URL state, etc... This happens for every condition that's been clicked. You cannot parallelize client-side (run in the browser) JavaScript. Everything runs sequentially, so one slow step affects the _whole_ application. Some of those slow steps involve libraries like NGL.js that I have no control over. To ameliorate this (2), I added some logic to make the legend update _before_ the rest of the application updates. This address the lag in legend's UI, but it won't make updates in the rest of the application faster.

I am working on making everything faster as a whole, but that requires big changes to the logic and organziation of the code.

**Comment by jbloom** [comment]
@WillHannon-MCB, this is actually great. Just adding the `double-click` makes a big difference as now even if it is a big slow you can select a dataset with just one command. So I feel like this is actually a big improvement already. The biggest problem was not the lag, but just having to click on say 7 things to deselect them if you just wanted to show one.

So speeding up will be great, but this already makes it much better, thanks!

I do wonder if it might be possible to somehow document this better on the tool, as it is not immediately obvious that `double-click` and `option click` do these things.
